-- 33社分のクライアントデータ（本番用）
-- ※ seed.sql の5社シードを投入後に実行するか、代わりに単独で使用してください
insert into clients (name, sort_order, enabled_tasks) values
  ('株式会社あおば商事', 1, '{true,true,true,true,true}'),
  ('有限会社いとう製作所', 2, '{true,true,false,true,true}'),
  ('合同会社ウィンテック', 3, '{true,true,true,false,true}'),
  ('株式会社エコライフ', 4, '{true,false,false,true,true}'),
  ('おか山クリニック', 5, '{true,true,true,true,false}'),
  ('株式会社かわさき物産', 6, '{true,true,true,true,true}'),
  ('有限会社きのした工業', 7, '{true,true,true,true,true}'),
  ('株式会社くろだ食品', 8, '{true,true,false,true,true}'),
  ('合同会社けいおう設計', 9, '{true,true,true,true,true}'),
  ('こまつ農園株式会社', 10, '{true,false,true,true,true}'),
  ('株式会社さいとう電機', 11, '{true,true,true,true,true}'),
  ('有限会社しみず不動産', 12, '{true,true,true,false,true}'),
  ('株式会社すずき商会', 13, '{true,true,true,true,true}'),
  ('せいわ建設株式会社', 14, '{true,true,true,true,true}'),
  ('有限会社そのだ印刷', 15, '{true,true,false,false,true}'),
  ('株式会社たかはし電設', 16, '{true,true,true,true,true}'),
  ('合同会社ちくば物流', 17, '{true,true,true,true,true}'),
  ('株式会社つばさ運輸', 18, '{true,false,true,true,true}'),
  ('有限会社てらだ金属', 19, '{true,true,true,true,true}'),
  ('とおやま医院', 20, '{true,true,true,true,false}'),
  ('株式会社なかがわ建材', 21, '{true,true,true,true,true}'),
  ('にしむら歯科医院', 22, '{true,true,true,true,false}'),
  ('株式会社ぬまた観光', 23, '{true,true,true,false,true}'),
  ('合同会社ねじめ技研', 24, '{true,true,true,true,true}'),
  ('のもと司法書士事務所', 25, '{true,false,false,true,true}'),
  ('株式会社はやし商店', 26, '{true,true,true,true,true}'),
  ('有限会社ひがし縫製', 27, '{true,true,false,true,true}'),
  ('ふじた整骨院', 28, '{true,true,true,true,false}'),
  ('株式会社へいわ食品', 29, '{true,true,true,true,true}'),
  ('ほんだ自動車整備', 30, '{true,false,true,true,true}'),
  ('株式会社まつもと薬局', 31, '{true,true,true,true,true}'),
  ('みやざき会計事務所', 32, '{true,true,true,false,true}'),
  ('むさしの農業組合', 33, '{true,true,true,true,true}');
